using System.Windows;

// Assembly metadata (title, company, version, etc.) is defined in NuixLogReviewer.csproj
// and generated by the SDK. Only the WPF ThemeInfo attribute needs to live here, since
// the SDK does not generate it.
[assembly: ThemeInfo(
    ResourceDictionaryLocation.None,           // where theme specific resource dictionaries are located
                                               // (used if a resource is not found in the page,
                                               //  or application resource dictionaries)
    ResourceDictionaryLocation.SourceAssembly  // where the generic resource dictionary is located
                                               // (used if a resource is not found in the page,
                                               //  app, or any theme specific resource dictionaries)
)]
